### ISSUE TITLE
Sort doesn't work after agg without ungroup

### ISSUE THREAD

**Issue by samarpan-rai** [koaning/clumper#41] opened 2020-08-18 19:23 UTC
I am not sure if this is a bug but it is definitely not a feature request so I am writing it as a bug report. 

**Problem**
I was expecting the following code to return a sorted list of the count grouped by the `primary_type` key but that is not the case. I see an unsorted list. Is this an expected behaviour?

```python
from clumper import Clumper
(
    Clumper.read_jsonl("https://calmcode.io/datasets/pokemon.jsonl")
    .mutate(primary_type = lambda c : c['type'][0])
    .group_by('primary_type')
    .agg(occurence = ('primary_type','count'))
    .sort(key=lambda x : x['occurence'])
    .collect()
)

```

**Additional context**

Adding `ungroup` after `agg` and before `sort` solves it. The following code produces what I want. 
```python
from clumper import Clumper

(
    Clumper.read_jsonl("https://calmcode.io/datasets/pokemon.jsonl")
    .mutate(primary_type = lambda c : c['type'][0])
    .group_by('primary_type')
    .agg(occurence = ('primary_type','count'))
    .ungroup()
    .sort(key=lambda x : x['occurence'])
    .collect()
)
```

**Comment by samukweku** [comment] 2020-08-19 01:39
Since it is a grouping I expect the sort to occur within each group. Is that what you get?

**Comment by samarpan-rai** [comment] 2020-08-19 07:17
@samukweku Maybe I didn't fully understand the difference. Can you give me an example  of within group sorting?

**Comment by samukweku** [comment] 2020-08-19 07:55
Try grouping by the `type`, after `explode`, and sort on the `total` key : 

```
(
    Clumper.read_jsonl("https://calmcode.io/datasets/pokemon.jsonl")
    .explode('type')
    .group_by('type')
    .sort(key=lambda x : x['total'])
    .collect()
)
```
the function you used is a reducing function - you get just one value per group... no point sorting within a group with a single value. Hope the code above explains better sorting within a group

**Comment by koaning** [comment] 2020-08-19 08:17
@samarpan-rai yeah I might argue this is expected behaviour. Just to check, have you seen [this guid on the docs](https://koaning.github.io/clumper/guides/understanding-groups.html)? 

The `.agg` operation **does not** remove the grouping. It's a bit of extra work but I found that in the end, groups should be dealt with explicitly. Otherwise the user might need to do a lot of accounting in their mind. 

@samukweku just mentioning it as a by the way, but on GitHub you can get pretty syntax highlighting for python if you add this at the start of a code snippet. 

    ```python

**Comment by samukweku** [comment] 2020-08-19 08:19
@koaning thanks for that. And to think I use it all the time when writing documentation.

**Comment by koaning** [comment] 2020-08-19 08:56
@samarpan-rai just to check, can I close this issue?

**Comment by samarpan-rai** [comment] 2020-08-19 09:09
> Try grouping by the `type`, after `explode`, and sort on the `total` key :
> 
> ```
> (
>     Clumper.read_jsonl("https://calmcode.io/datasets/pokemon.jsonl")
>     .explode('type')
>     .group_by('type')
>     .sort(key=lambda x : x['total'])
>     .collect()
> )
> ```
> 
> the function you used is a reducing function - you get just one value per group... no point sorting within a group with a single value. Hope the code above explains better sorting within a group

Yes, thank you! It indeed makes sense for within group sorting. 

> @samarpan-rai yeah I might argue this is expected behaviour. Just to check, have you seen [this guide on the docs](https://koaning.github.io/clumper/guides/understanding-groups.html)?
> The `.agg` operation **does not** remove the grouping. It's a bit of extra work but I found that in the end, groups should be dealt with explicitly. Otherwise the user might need to do a lot of accounting in their mind.

I did read it shortly but seem to have missed "With groups active, still perform the sorting but only within each group." I tried to transfer my experience from R's `dplyr` where one can do the following to get a sorted count by some grouping variable `name`.
```R
df %>%
  group_by(name) %>%
  count(name) %>%
  arrange(n)
```

**Comment by samarpan-rai** [comment] 2020-08-19 09:11
> @samarpan-rai just to check, can I close this issue?

Yes

**Closed** 2020-08-19 09:25 UTC
